GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json 

{
    "id": 5,
    "name": "Ivar",
    "age": 29,
    "food": "Kebab"
}

###

PUT http://localhost:3000/api/users/1
Content-Type: application/json 

{
    "name": "Ny Anton",
    "age": 80,
    "food": "Uppdaterad mat"
}

###

DELETE http://localhost:3000/api/users/4
